In [ ]:
#1
symbols="$*&!@"
codes=[]
for symbol in symbols:
  codes.append(ord(symbol))
print(codes)

[36, 42, 38, 33, 64]


In [ ]:
#2
symbols="$*&!@"
codes=[ord(symbol)for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]


In [ ]:
#3
x="!~$$*&!@"
dummy=[ord(x) for x in x]

print(x)
print(dummy)

!~$$*&!@
[33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#4
symbols='"!~$$*&!@'
beyond_ascii=[ord(s) for s in symbols if ord(s)> 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#5
symbols="!~$$*&!@"
beyond_ascii=list(filter(lambda c: c>64, map(ord,symbols)))
print(beyond_ascii,'\n')

print(f"Map function:\n>>> {map(ord,symbols)}")
print(f"List after map:\n {list(map(ord,symbols))}")

[126] 

Map function:
>>> <map object at 0x7be644bb1c00>
List after map:
 [33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#6
colors=['black','white']
sizes=['s','m','l']
tshirts=[(color,size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color,size))


[('black', 's'), ('black', 'm'), ('black', 'l'), ('white', 's'), ('white', 'm'), ('white', 'l')]
('black', 's')
('black', 'm')
('black', 'l')
('white', 's')
('white', 'm')
('white', 'l')


In [ ]:
#7
symbols="!#^&&#"
ord_s=tuple(ord(s) for s in symbols if ord(s))
print(ord_s)

(33, 35, 94, 38, 38, 35)


In [ ]:
#8
colors= ['black','white']
sizes=['S','M','L']
for tshirt in ('{}{}'.format(c,s) for s in sizes for c in colors):
  print(tshirt)

blackS
whiteS
blackM
whiteM
blackL
whiteL


In [ ]:
#9
lax_coordinates=(33.9425,-118.408056)
city, year, pop,chg,area=('Tokyo',2003,32450,0.66,8014)
traveler_ids=[("USA",'31195855'),
              ('BRA','CE342567'),
              ('ESP','XDA205856')]
for passport in sorted(traveler_ids):
  print("%s%s"%passport)
  print('{}{}'.format(passport[0],passport[1]))
  print(f'{passport[0]}/{passport[1]}')

BRACE342567
BRACE342567
BRA/CE342567
ESPXDA205856
ESPXDA205856
ESP/XDA205856
USA31195855
USA31195855
USA/31195855


In [ ]:
#10
for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [ ]:
#11
lax_coordinates=(33.9425,-118.408056)
latitude, longtitude=lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [ ]:
#12
a=10; b=20
b,a=a,b
print(a,b)

20 10


In [ ]:
#13
divmod(20,8)

t=(20,8)
divmod(*t)

quotient,remainder= divmod(*t)
quotient,remainder

(2, 4)

In [ ]:
#14
import os
_, filename=os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [ ]:
#15
a,b,*rest=range(5)
a,b,rest


(0, 1, [2])

In [ ]:
a,b,*rest=range(3)
a,b,rest

(0, 1, [2])

In [ ]:
a,b,*rest=range(2)
a,b,rest

(0, 1, [])

In [ ]:
#16
a,*body,c,d=range(5)
a,body,c,d

(0, [1, 2], 3, 4)

In [ ]:
*heat,b,c,d=range(5)
heat,b,c,d

([0, 1], 2, 3, 4)

In [ ]:
#17
metro_areas=[("Tokyo","JP",36.933,(35,139)),
             ("Delhi NCR", "IN", 21, (19, 77)),
             ("Mexico City","MX",20,(19,-99)),
             ("New York-Newark","US",20,(40,-74)),
             ("Sao Paulo","BR",19,(-23,-46))]
print("{:15}|{:^9}|{:^9}".format('', 'lat.', 'long.'))
fmt='{:15}|{:^9.4f}|{:9.4f}'

for name,cc,pop,(lat,longi) in metro_areas:
  if longi <=0:
    print(fmt.format(name,lat,longi))

               |  lat.   |  long.  
Mexico City    | 19.0000 | -99.0000
New York-Newark| 40.0000 | -74.0000
Sao Paulo      |-23.0000 | -46.0000


In [ ]:
#18
from collections import namedtuple

City = namedtuple('City', 'name country population1 population2 coordinates')

tokyo = City('Tokyo', 'JP', 35, 933, (35.689, 139.691))
tokyo

City(name='Tokyo', country='JP', population1=35, population2=933, coordinates=(35.689, 139.691))

In [ ]:
#19
City._fields

('name', 'country', 'population', 'coordinates')

In [ ]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [ ]:
for key,value in delhi._asdict().items():
  print(key+':',value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [ ]:
#20
l=[10,20,30,40,50,60]
l[:2]

[10, 20]

In [ ]:
l[2:]

[30, 40, 50, 60]

In [ ]:
l[:3]

[10, 20, 30]

In [ ]:
l[3:]

[40, 50, 60]

In [ ]:
#21
invoice="""
0.....6......................25.........33.........40...........
1909  Pimoroni            $17.50    3      $52.50
1489  6mm Tactile         $4.95     3     $9.90"""

SKU=slice(0,6)
DESCRIPTION=slice(6,25)
UNIT_PRICE=slice(25,33)
QUANTITY=slice(33,40)
ITEM_TOTAL=slice(40,None)

line_item = invoice.split('\n')[2:]

for item in line_item:
  print(item[UNIT_PRICE],item[DESCRIPTION])



 $17.50  Pimoroni           
 $4.95   6mm Tactile        


In [ ]:
#22
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
l[2:5]=[20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [ ]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [ ]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [ ]:
#23
l[2:5]=100


TypeError: must assign iterable to extended slice

In [ ]:
#24
l[2:5]=[100]
l

[0, 1, 100, 22, 9]

In [ ]:
#25
l=[1,2,3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [ ]:
#26
board=[['_'] *3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [ ]:
board[1][2]='X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [ ]:
#27
weird_board=[['_']*3]*3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [ ]:
weird_board[1][2]='0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [ ]:
#28
row=['_']*3
board=[]
for i in range(3):
  board.append(row)
board[1][2]='X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [ ]:
#29
board=[]
for i in range(3):
  row=['_']*3
  board.append(row)
print(board)
board[2][0]='X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [1]:
#30
l=[1,2,3]
id(l)

134540019854208

In [2]:
l*=2
l

[1, 2, 3, 1, 2, 3]

In [3]:
id(l)

134540019854208

In [4]:
#31
t=(1,2,3)
id(t)

134540019710976

In [5]:
t*=2
id(t)

134540254354720

In [6]:
#32
t=(1,2,[30,40])
print(t)
t[2]+=[50,60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [7]:
#33
print(t)

(1, 2, [30, 40, 50, 60])


In [8]:
#34
fruits=['grape','rasberry','apple','banana']
sorted(fruits)

['apple', 'banana', 'grape', 'rasberry']

In [9]:
fruits

['grape', 'rasberry', 'apple', 'banana']

In [10]:
sorted(fruits,reverse=True)

['rasberry', 'grape', 'banana', 'apple']

In [11]:
sorted(fruits,key=len)

['grape', 'apple', 'banana', 'rasberry']

In [12]:
#35
sorted(fruits,reverse=True,key=len)

['rasberry', 'banana', 'grape', 'apple']

In [13]:
fruits

['grape', 'rasberry', 'apple', 'banana']

In [18]:
fruits.sort()

In [24]:
#36
from array import array
from random import random

floats = array('d',(random() for _ in range(10**7)))
floats[-1]

0.07125485576172474

In [26]:
 #37
with open('floats.bin','wb') as f:
  floats.tofile(f)

floats2=array('d')
with open('floats.bin','rb') as f:
  floats2.fromfile(f,10**7)

floats2[-1]


0.07125485576172474

In [29]:
#38
import array
numbers= array.array('h',[-2, -1, 0, 1, 2])
memv=memoryview(numbers)
len(memv)

5

In [31]:
memv[0]

-2

In [32]:
memv_oct=memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [33]:
memv_oct[5]=4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [35]:
#39
import numpy
a= numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
type(a)

numpy.ndarray

In [37]:
#40
a.shape

(12,)

In [38]:
a.shape=3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
#41
a[2]


array([ 8,  9, 10, 11])

In [40]:
a[2,1]

np.int64(9)

In [41]:
a[:,1]

array([1, 5, 9])

In [42]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])